/**
 * Extracted visualizer styles. Generated by scripts/extract-styles.js
 * Run 'node scripts/extract-styles.js' after modifying CSS in htmlBuilder.
 */

export function getVisualizerStyles(): string {
    return `
* {
        font-family: var(--vscode-font-family), -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
        box-sizing: border-box;
    }
    html, body {
        margin: 0;
        padding: 0;
        height: 100%;
        overflow: hidden;
    }
    body {
        display: flex;
        flex-direction: column;
        padding: 20px;
        font-size: 13px;
        font-weight: 400;
        line-height: 1.5;
        background-color: var(--vscode-editor-background);
        color: var(--vscode-editor-foreground);
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;
    }
    #controls {
        flex-shrink: 0;
        margin-bottom: 8px;
        padding: 8px 12px;
        background: var(--vscode-editor-background);
        border: 1px solid var(--vscode-panel-border);
        border-radius: 4px;
    }
    button {
        margin-right: 4px;
        padding: 5px 10px;
        background-color: var(--vscode-button-background);
        color: var(--vscode-button-foreground);
        border: 1px solid transparent;
        border-radius: 4px;
        cursor: pointer;
        font-size: 11px;
        font-weight: 500;
        line-height: 1.2;
        letter-spacing: 0.02em;
        transition: all 0.15s ease;
        display: inline-flex;
        align-items: center;
        gap: 4px;
        position: relative;
        overflow: hidden;
        white-space: nowrap;
    }
    button:hover {
        background-color: var(--vscode-button-hoverBackground);
        box-shadow: 0 1px 3px rgba(0,0,0,0.12);
    }
    button:active {
        opacity: 0.9;
    }
    .view-btn {
        background: var(--vscode-button-secondaryBackground, var(--vscode-input-background));
        color: var(--vscode-button-secondaryForeground, var(--vscode-foreground));
        border: 1px solid var(--vscode-input-border, var(--vscode-panel-border));
        font-weight: 500;
        padding: 5px 10px;
    }
    .view-btn:hover {
        background: var(--vscode-button-secondaryHoverBackground, var(--vscode-list-hoverBackground));
        border-color: var(--vscode-focusBorder);
    }
    .view-btn-active {
        background: var(--vscode-button-background) !important;
        color: var(--vscode-button-foreground) !important;
        border-color: var(--vscode-button-background) !important;
    }
    .view-dropdown {
        position: relative;
        display: inline-flex;
        align-items: stretch;
    }
    .view-dropdown-menu {
        position: absolute;
        top: calc(100% + 4px);
        left: 0;
        min-width: 180px;
        background: var(--vscode-menu-background, var(--vscode-dropdown-background));
        border: 1px solid var(--vscode-menu-border, var(--vscode-panel-border));
        border-radius: 4px;
        box-shadow: 0 4px 12px rgba(0,0,0,0.2);
        padding: 4px;
        display: none;
        flex-direction: column;
        gap: 1px;
        z-index: 600;
    }
    .view-dropdown-menu.show {
        display: flex;
    }
    .view-dropdown-item {
        display: flex;
        align-items: center;
        gap: 6px;
        width: 100%;
        justify-content: flex-start;
        padding: 6px 10px;
        margin: 0;
        border: none;
        border-radius: 3px;
        background: none;
        color: var(--vscode-menu-foreground, var(--vscode-foreground));
        font-size: 11px;
        font-weight: 400;
        line-height: 1.3;
        cursor: pointer;
        text-align: left;
        transition: background 0.1s ease;
    }
    .view-dropdown-item .icon,
    .view-dropdown-item .codicon {
        display: inline-block;
        width: 14px;
        text-align: center;
        flex-shrink: 0;
    }
    #controls .codicon {
        font-size: 14px;
    }
    .view-dropdown-item:hover {
        background-color: var(--vscode-list-hoverBackground);
    }
    .view-dropdown-item.active {
        background: var(--vscode-list-activeSelectionBackground);
        color: var(--vscode-list-activeSelectionForeground);
        font-weight: 500;
    }
    .export-dropdown {
        position: relative;
        display: inline-block;
    }
    .export-menu {
        display: none;
        position: fixed;
        background-color: var(--vscode-menu-background);
        border: 1px solid var(--vscode-menu-border);
        border-radius: 4px;
        box-shadow: 0 4px 12px rgba(0,0,0,0.2);
        min-width: 130px;
        width: 130px;
        z-index: 10000;
        padding: 4px;
    }
    @keyframes dropdown-appear {
        from {
            opacity: 0;
            transform: translateY(-12px) scale(0.92);
            filter: blur(4px);
        }
        to {
            opacity: 1;
            transform: translateY(0) scale(1);
            filter: blur(0);
        }
    }

    .export-menu.show {
        display: block;
    }
    .export-menu-item {
        display: block;
        width: 100%;
        padding: 6px 10px;
        margin: 0;
        text-align: left;
        background: none;
        border: none;
        border-radius: 3px;
        color: var(--vscode-menu-foreground);
        font-size: 11px;
        font-weight: 400;
        line-height: 1.2;
        transition: background-color 0.1s ease;
    }
    .export-menu-item:hover {
        background-color: var(--vscode-list-hoverBackground);
    }
    .export-menu-item:first-child {
        border-top-left-radius: 3px;
        border-top-right-radius: 3px;
    }
    .export-menu-item:last-child {
        border-bottom-left-radius: 3px;
        border-bottom-right-radius: 3px;
    }
    .export-submenu-container {
        position: relative;
    }
    .export-submenu-container .export-menu-item::after {
        content: '▸';
        float: right;
        margin-left: 8px;
    }
    .export-submenu {
        display: none;
        position: absolute;
        left: 100%;
        top: 0;
        background-color: var(--vscode-menu-background);
        border: 1px solid var(--vscode-menu-border);
        border-radius: 4px;
        box-shadow: 0 4px 12px rgba(0,0,0,0.2);
        min-width: 140px;
        z-index: 10001;
        padding: 4px;
    }
    .export-submenu-container:hover .export-submenu {
        display: block;
    }
    .action-btn {
        background: var(--vscode-button-secondaryBackground, var(--vscode-input-background));
        color: var(--vscode-button-secondaryForeground, var(--vscode-foreground));
        border: 1px solid var(--vscode-input-border, var(--vscode-panel-border));
        padding: 4px 8px;
        font-size: 11px;
    }
    .action-btn:hover {
        background-color: var(--vscode-button-secondaryHoverBackground, var(--vscode-list-hoverBackground));
        border-color: var(--vscode-focusBorder);
    }
    .primary-btn {
        background: var(--vscode-button-background);
        color: var(--vscode-button-foreground);
        border: 1px solid transparent;
        padding: 4px 8px;
        font-size: 11px;
    }
    .primary-btn:hover {
        background-color: var(--vscode-button-hoverBackground);
    }
    #visualization-wrapper {
        position: relative;
        flex: 1;
        min-height: 0;
        width: 100%;
        overflow: hidden;
    }
    #pkg-dropdown {
        position: absolute;
        top: 8px;
        left: 12px;
        z-index: 500;
        display: none;
        align-items: center;
        gap: 8px;
    }
    #pkg-dropdown .view-dropdown-menu {
        position: absolute;
        top: calc(100% + 4px);
        left: 0;
    }
    #visualization {
        width: 100%;
        height: 100%;
        border: 1px solid var(--vscode-panel-border);
        border-radius: 4px;
        overflow: hidden;
        position: relative;
    }
    #legend-popup {
        display: none;
        position: absolute;
        top: 12px;
        right: 12px;
        z-index: 1000;
        background: var(--vscode-editor-background);
        border: 1px solid var(--vscode-panel-border);
        border-radius: 6px;
        box-shadow: 0 4px 16px rgba(0,0,0,0.3);
        padding: 14px 18px;
        min-width: 240px;
        max-width: 320px;
        font-size: 12px;
        color: var(--vscode-editor-foreground);
    }
    /* Loading overlay styles */
    #loading-overlay {
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background: var(--vscode-editor-background);
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        z-index: 1000;
        border-radius: 8px;
        border: 1px solid var(--vscode-panel-border);
    }
    #loading-overlay.hidden {
        display: none;
    }
    .loading-spinner {
        width: 48px;
        height: 48px;
        border: 3px solid var(--vscode-panel-border);
        border-top-color: var(--vscode-button-background);
        border-radius: 50%;
        animation: spin 1s linear infinite;
        margin-bottom: 16px;
    }
    @keyframes spin {
        to { transform: rotate(360deg); }
    }
    .loading-text {
        font-size: 14px;
        color: var(--vscode-foreground);
        margin-bottom: 12px;
        font-weight: 500;
    }
    .loading-progress-container {
        width: 200px;
        height: 4px;
        background: var(--vscode-panel-border);
        border-radius: 2px;
        overflow: hidden;
    }
    .loading-progress-bar {
        height: 100%;
        width: 30%;
        background: linear-gradient(90deg, var(--vscode-button-background), var(--vscode-button-hoverBackground));
        border-radius: 2px;
        animation: progress-indeterminate 1.5s ease-in-out infinite;
    }
    @keyframes progress-indeterminate {
        0% { transform: translateX(-100%); width: 30%; }
        50% { transform: translateX(150%); width: 50%; }
        100% { transform: translateX(400%); width: 30%; }
    }
    #visualization.structural-transition-active {
        will-change: opacity, transform;
    }
    #visualization.structural-transition-active.fade-out {
        opacity: 0;
        transform: scale(0.98);
    }
    #visualization.structural-transition-active.fade-in {
        opacity: 1;
        transform: scale(1);
    }
    #visualization svg {
        display: block;
        width: 100%;
        height: 100%;
    }
    .node-group {
        cursor: pointer;
    }
    .node-group:hover .node-background {
        stroke-width: 2px !important;
        opacity: 1 !important;
    }
    .node {
        cursor: pointer;
        fill: var(--vscode-editor-selectionBackground);
        stroke: var(--vscode-editor-foreground);
        stroke-width: 2px;
    }
    .node:hover {
        fill: var(--vscode-editor-selectionHighlightBackground);
        stroke-width: 3px;
    }
    .node-background {
        transition: all 0.2s ease;
    }
    .node-label {
        fill: var(--vscode-editor-foreground);
        font-size: 12px;
        font-family: var(--vscode-font-family);
        pointer-events: none;
        dominant-baseline: central;
    }
    .node-type {
        fill: var(--vscode-descriptionForeground);
        font-size: 10px;
        font-family: var(--vscode-font-family);
        pointer-events: none;
        dominant-baseline: central;
    }
    .node-children {
        fill: var(--vscode-descriptionForeground);
        font-size: 9px;
        font-family: var(--vscode-font-family);
        pointer-events: none;
        opacity: 0.7;
    }
    .graph-node-group {
        cursor: pointer;
    }
    .graph-node-group:hover .graph-node-background {
        stroke-width: 2px !important;
        opacity: 1 !important;
    }
    .graph-node-background {
        transition: all 0.2s ease;
    }
    .hierarchy-cell:hover rect {
        stroke-width: 2px;
        opacity: 1;
        transform: scale(1.02);
        transition: all 0.2s ease;
    }
    .hierarchy-cell rect {
        transition: all 0.2s ease;
    }
    .hierarchy-cell .node-label {
        fill: var(--vscode-editor-foreground);
        font-size: 13px;
        font-weight: 600;
        pointer-events: none;
        dominant-baseline: central;
    }
    .hierarchy-cell .node-type {
        fill: var(--vscode-descriptionForeground);
        font-size: 11px;
        font-weight: 500;
        pointer-events: none;
        dominant-baseline: central;
    }
    .hierarchy-card-title {
        fill: var(--vscode-editor-foreground);
        font-size: 13px;
        font-weight: 600;
    }
    .hierarchy-card-type {
        fill: var(--vscode-descriptionForeground);
        font-size: 11px;
        font-style: italic;
    }
    .hierarchy-section-title {
        fill: var(--vscode-descriptionForeground);
        font-size: 11px;
        font-weight: 600;
        text-transform: uppercase;
        letter-spacing: 0.04em;
    }
    .hierarchy-detail-text {
        fill: var(--vscode-editor-foreground);
        font-size: 11px;
    }
    .hierarchy-stat-pill-bg {
        fill: rgba(255, 255, 255, 0.05);
        stroke: var(--vscode-panel-border);
        stroke-width: 1px;
    }
    .hierarchy-stat-pill-label {
        fill: var(--vscode-editor-foreground);
        font-size: 10px;
        font-weight: 600;
    }
    .hierarchy-child-card rect {
        fill: rgba(255, 255, 255, 0.04);
        stroke: var(--vscode-panel-border);
        stroke-width: 1px;
        rx: 4px;
        ry: 4px;
    }
    .hierarchy-child-card text {
        fill: var(--vscode-editor-foreground);
        font-size: 10px;
        font-weight: 500;
    }
    .view-btn-active {
        background: var(--vscode-button-background) !important;
        color: var(--vscode-button-foreground) !important;
        border: 2px solid var(--vscode-charts-blue) !important;
        font-weight: bold !important;
        box-shadow: 0 0 4px var(--vscode-charts-blue) !important;
    }
    .highlighted-element {
        filter: drop-shadow(0 0 10px #FFD700);
    }
    .highlighted-element .node-background,
    .highlighted-element .graph-node-background,
    .highlighted-element rect {
        stroke: #FFD700 !important;
        stroke-width: 3px !important;
        opacity: 1 !important;
    }
    .highlighted-element .node {
        stroke: #FFD700 !important;
        stroke-width: 4px !important;
        fill: #FFD700 !important;
    }
    .node-group.highlighted-element .node-background {
        stroke: #FFD700 !important;
        stroke-width: 3px !important;
        filter: drop-shadow(0 0 8px #FFD700);
    }
    .element-pulse {
        pointer-events: none;
    }
    .link {
        fill: none;
        stroke: var(--vscode-editor-foreground);
        stroke-width: 1.5px;
        opacity: 0.6;
    }
    .relationship-link {
        fill: none;
        stroke: var(--vscode-charts-red);
        stroke-width: 2px;
        stroke-dasharray: 5, 5;
        opacity: 0.5;
    }

    #sysml-cytoscape {
        width: 100%;
        height: 100%;
    }
`;
}
