#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

const htmlBuilderPath = path.join(__dirname, '..', 'src', 'visualization', 'htmlBuilder.ts');
const content = fs.readFileSync(htmlBuilderPath, 'utf8');

const styleStart = content.indexOf('<style nonce="${nonce}">');
const styleEnd = content.indexOf('</style>', styleStart);
if (styleStart === -1 || styleEnd === -1) {
    console.log('No inline style block found in htmlBuilder (CSS already in styles.ts)');
    process.exit(0);
}

// Extract CSS: from newline after opening tag to before </style>
const cssStart = content.indexOf('\n', styleStart) + 1;
const cssContent = content.substring(cssStart, styleEnd).trim();

const stylesPath = path.join(__dirname, '..', 'src', 'visualization', 'styles.ts');
const stylesOutput = `/**
 * Extracted visualizer styles. Generated by scripts/extract-styles.js
 * Run 'node scripts/extract-styles.js' after modifying CSS in htmlBuilder.
 */

export function getVisualizerStyles(): string {
    return \`
${cssContent}
\`;
}
`;
fs.writeFileSync(stylesPath, stylesOutput, 'utf8');
console.log('Wrote styles.ts, CSS length:', cssContent.length);
